object Versions {
  lazy val akkaHttpVersion        = "10.2.6"
  lazy val akkaManagementVersion  = "1.1.1"
  lazy val akkaVersion            = "2.6.17"
  lazy val bouncycastleVersion    = "1.70"
  lazy val catsVersion            = "2.7.0"
  lazy val awsDynamoDBVersion     = "2.17.157"
  lazy val httpJson4sVersion      = "1.38.2"
  lazy val jacksonVersion         = "2.13.0"
  lazy val jdbcPersistenceVersion = "5.0.2"
  lazy val json4sVersion          = "4.0.4"
  lazy val kamonVersion           = "2.5.0"
  lazy val logbackVersion         = "1.2.11"
  lazy val mongoDBVersion         = "4.5.1"
  lazy val mustacheVersion        = "0.9.10"
  lazy val nimbusVersion          = "9.21"
  lazy val openapi4jVersion       = "1.0.7"
  lazy val postgresVersion        = "42.3.3"
  lazy val projectionVersion      = "1.2.2"
  lazy val s3Persistence          = "1.1.74"
  lazy val scalaMockVersion       = "5.2.0"
  lazy val scalapbVersion         = "0.11.1"
  lazy val scalatestVersion       = "3.2.11"
  lazy val slickProjectionVersion = "1.2.2"
  lazy val slickVersion           = "3.3.3"
}

object PagopaVersions {
  lazy val commonsVersion = "0.1.x-SNAPSHOT"
}
