/**
 * Notification Notifier Micro Service
 * This service notifies organization about occurred platform events
 *
 * The version of the OpenAPI document: {{version}}
 * Contact: support@example.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.pagopa.interop.notifier.client.model

import it.pagopa.interop.notifier.client.invoker.ApiModel

case class Problem(
  /* URI reference of type definition */
  `type`: String,
  /* The HTTP status code generated by the origin server for this occurrence of the problem. */
  status: Int,
  /* A short, summary of the problem type. Written in english and readable */
  title: String,
  /* A human readable explanation of the problem. */
  detail: Option[String] = None,
  errors: Seq[ProblemError]
) extends ApiModel
